# cspell:words gunicorn multiproc noninteractive trixie

FROM python:3.13-trixie



# Install tools
RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt install --yes curl

# Set up home directory
WORKDIR /srv/application

# Set up the python virtual environment
RUN python3 -m venv venv
RUN venv/bin/python -m pip install --upgrade pip wheel
COPY pip.conf /srv/application/venv/pip.conf

# Copy the application sources
RUN mkdir --parents /srv/application_sources
COPY Automation/ /srv/application_sources/Automation/
COPY Website/ /srv/application_sources/Website/
COPY ProjectConfiguration.json /srv/application_sources/

# Install the application and gunicorn
RUN venv/bin/python -m pip install --upgrade /srv/application_sources/Website "gunicorn ~= 23.0.0"

# Configure directory for prometheus metrics
RUN mkdir --parents /srv/prometheus
ENV PROMETHEUS_MULTIPROC_DIR=/srv/prometheus



# Open network port
EXPOSE 80

# Run gunicorn
CMD [ "/srv/application/.venv/bin/gunicorn", "--bind", "0.0.0.0:80", "--config", "/srv/gunicorn_configuration.py" ]
