# Configuration for Apache Web Server

# Process
DefaultRuntimeDir "${APACHE_RUN_DIR}"
PidFile "${APACHE_PID_FILE}"
User "${APACHE_RUN_USER}"
Group "${APACHE_RUN_GROUP}"

# Logging
LogLevel info
LogFormat "%{%Y-%m-%d %H:%M:%S}t (%a:%{remote}p, %L) %r (Status: %>s, Size: %B B, Time: %{ms}T ms)" common
ErrorLogFormat "%{c}t (%a, %L) [%l][%m] %M"
ErrorLog "${APACHE_LOG_DIR}/error.log"
CustomLog "${APACHE_LOG_DIR}/access.log" common

# Requests
HostnameLookups Off
KeepAlive On
KeepAliveTimeout 5
MaxKeepAliveRequests 100
Timeout 300

# Modules
IncludeOptional "mods-enabled/*.load"
IncludeOptional "mods-enabled/*.conf"

# Ports
Listen 80
Listen 443

# Default server name
ServerName localhost

# Default access rules
AccessFileName .htaccess

<Directory "/">
	Require all denied
	AllowOverride None
</Directory>

<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>

# Additional configuration
IncludeOptional "conf-enabled/*.conf"
IncludeOptional "sites-enabled/*.conf"
