# cspell:words snakeoil

# Configuration for the default website in Apache web server

<VirtualHost *:443>
	ErrorLog "${APACHE_LOG_DIR}/error.log"
	CustomLog "${APACHE_LOG_DIR}/access.log" common

	SSLEngine on
	SSLCertificateFile "/etc/ssl/certs/ssl-cert-snakeoil.pem"
	SSLCertificateKeyFile "/etc/ssl/private/ssl-cert-snakeoil.key"

	DocumentRoot "/var/www/html"

	<Directory "/var/www/html">
		Require all denied
		AllowOverride None
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ErrorLog "${APACHE_LOG_DIR}/error.log"
	CustomLog "${APACHE_LOG_DIR}/access.log" common

	DocumentRoot "/var/www/html"

	<Directory "/var/www/html">
		Require all denied
		AllowOverride None
	</Directory>
</VirtualHost>
