# cspell:words wsgi

# Configuration for the application website in Apache web server

<VirtualHost *:443>

	SSLEngine on
	SSLCertificateFile "/etc/ssl/local/developer-local.benjaminhamon.com.crt"
	SSLCertificateKeyFile "/etc/ssl/local/developer-local.benjaminhamon.com.key"

	WSGIScriptAlias "/" "/srv/scripts/website.wsgi"
	WSGIPassAuthorization On

	<Directory "/srv/scripts">
		Require all granted
	</Directory>
</VirtualHost>

<VirtualHost *:80>

	RewriteEngine On
	RewriteCond %{HTTPS} off
	RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}

</VirtualHost>
