# cspell:words venv wsgi

# Configuration for the application website in Apache web server

<VirtualHost *:80>

	WSGIDaemonProcess website python-home=/srv/application/.venv
	WSGIProcessGroup website
	WSGIApplicationGroup %{GLOBAL}

	WSGIScriptAlias "/" "/srv/scripts/website.wsgi"
	WSGIPassAuthorization On

	<Directory "/srv/scripts">
		Require all granted
	</Directory>

</VirtualHost>
