- name: "Development Toolkit"
  website: "https://github.com/BenjaminHamon/DevelopmentToolkit"
  description: |-
    A toolkit for software development scripts.

- name: "Image Manager"
  website: "https://github.com/BenjaminHamon/Overmind.ImageManager"
  description: |-
    A Windows desktop application to manage your collections of pictures.

- name: "Job Orchestra"
  website: "https://github.com/BenjaminHamon/JobOrchestra"
  description: |-
    A toolkit for building a service which manages distributed job execution across a computer network. It is particularly suited as a base for making a continuous integration and delivery system that suits your team needs.

- name: "My Website"
  website: "https://github.com/BenjaminHamon/MyWebsite"
  description: |-
    This website.
