# cspell:words setuptools

[build-system]
requires = [ "setuptools ~= 82.0.1" ]
build-backend = "setuptools.build_meta"

[project]
name = "benjaminhamon-developer-website"
version = "6.0.0+development"
description = "Developer website for Benjamin Hamon"
requires-python = ">= 3.11"

authors = [
    { name = "Benjamin Hamon", email = "development@benjaminhamon.com" }
]

maintainers = [
    { name = "Benjamin Hamon", email = "development@benjaminhamon.com" }
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "benjaminhamon-standard-extensions ~= 1.0.1",
    "Flask ~= 3.1.3",
    "prometheus-flask-exporter ~= 0.23.2",
]

[project.optional-dependencies]
dev = [
    "mockito ~= 2.0.4",
    "pylint ~= 4.0.5",
    "pytest ~= 9.0.3",
    "pytest-asyncio ~= 1.3.0",
    "pytest-json ~= 0.4.0",
    "requests ~= 2.33.1",
]

[project.urls]
"Source" = "https://github.com/BenjaminHamon/DeveloperWebsite"

[tool.setuptools]
license-files = [ "../About.md", "../License.txt" ]

[tool.setuptools.packages.find]
include = [ "benjaminhamon_developer_website", "benjaminhamon_developer_website.*" ]

[tool.setuptools.package-data]
benjaminhamon_developer_website = [
    "static/**/*.css",
    "static/**/*.jpeg",
    "static/**/*.pdf",
    "static/**/*.png",
    "static/**/*.svg",
    "templates/**/*.html",
]
